#pragma once

#include <cstdint>
#include <string>
#include <vector>
#include "exchange.pb.h"

// Pull in protobuf-generated enums (Side, OrderType, OrderStatus, RejectionReason)
// so we don't duplicate them. The proto enums live in namespace exchange::.
// We forward-declare what we need and include the full header in .cpp files.
//
// IMPORTANT: Do NOT redefine Side, OrderType, OrderStatus, or RejectionReason
// here — they are generated by protobuf in exchange.pb.h.

namespace exchange {

// ============================================================
// Forward-declare the proto-generated enums so this header
// can be used without including the heavy exchange.pb.h.
// These match the proto definitions exactly.
// ============================================================

// We use plain enums (matching protobuf's generated code) with int type.
// The actual definitions come from exchange.pb.h; here we just declare
// the values we need for the struct defaults.

// Side
enum Side : int;
// OrderType
enum OrderType : int;
// OrderStatus
enum OrderStatus : int;
// RejectionReason
enum RejectionReason : int;

// ============================================================
// Core structs
// ============================================================

struct Order {
    std::string  order_id;
    std::string  user_id;
    std::string  symbol;
    int          side        = 0;  // exchange::SIDE_UNKNOWN
    int          type        = 1;  // exchange::LIMIT
    int          status      = 7;  // exchange::PENDING
    double       price       = 0.0;
    double       stop_price  = 0.0;   // For STOP_LOSS / STOP_LIMIT
    int          quantity    = 0;
    int          filled_qty  = 0;
    int          remaining   = 0;
    double       avg_fill_px = 0.0;
    int64_t      timestamp_ns = 0;
    int64_t      expire_time_ms = 0;  // For GTT; 0 = no expiry
    bool         is_active   = true;
};

struct ExecutedTrade {
    std::string trade_id;
    std::string symbol;
    double      price         = 0.0;
    int         quantity      = 0;
    std::string buy_order_id;
    std::string sell_order_id;
    std::string buyer_user_id;
    std::string seller_user_id;
    int64_t     timestamp_ns  = 0;
};

struct BookLevel {
    double price          = 0.0;
    int    total_quantity = 0;
    int    order_count    = 0;
};

struct BookSnapshot {
    std::string              symbol;
    std::vector<BookLevel>   bids;      // descending
    std::vector<BookLevel>   asks;      // ascending
    double                   best_bid   = 0.0;
    double                   best_ask   = 0.0;
    double                   spread     = 0.0;
    double                   mid_price  = 0.0;
    int64_t                  seq_num    = 0;
    int64_t                  timestamp_ns = 0;
};

struct MatchResult {
    int             status          = 7;  // PENDING
    int             rejection       = 0;  // REASON_NONE
    std::string     rejection_msg;
    std::vector<ExecutedTrade> trades;
    int             filled_qty      = 0;
    int             remaining_qty   = 0;
    double          avg_fill_price  = 0.0;
    int64_t         matching_latency_ns = 0;
};

struct InternalMarketStats {
    std::string symbol;
    double last_price   = 0.0;
    double open_price   = 0.0;
    double high_price   = 0.0;
    double low_price    = 0.0;
    int64_t volume      = 0;
    double  vwap        = 0.0;
    double  spread      = 0.0;
    double  order_imbalance = 0.0;
    int64_t trade_count = 0;
    bool    is_halted   = false;
};

} // namespace exchange
