# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exchange_pb2 as exchange__pb2


class ExchangeServiceStub(object):
    """============================================================
    Core Service Definition
    ============================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitOrder = channel.unary_unary(
                '/exchange.ExchangeService/SubmitOrder',
                request_serializer=exchange__pb2.OrderRequest.SerializeToString,
                response_deserializer=exchange__pb2.OrderResponse.FromString,
                )
        self.CancelOrder = channel.unary_unary(
                '/exchange.ExchangeService/CancelOrder',
                request_serializer=exchange__pb2.CancelRequest.SerializeToString,
                response_deserializer=exchange__pb2.CancelResponse.FromString,
                )
        self.AmendOrder = channel.unary_unary(
                '/exchange.ExchangeService/AmendOrder',
                request_serializer=exchange__pb2.AmendRequest.SerializeToString,
                response_deserializer=exchange__pb2.OrderResponse.FromString,
                )
        self.GetOrderBook = channel.unary_unary(
                '/exchange.ExchangeService/GetOrderBook',
                request_serializer=exchange__pb2.OrderBookRequest.SerializeToString,
                response_deserializer=exchange__pb2.OrderBookSnapshot.FromString,
                )
        self.GetMarketStats = channel.unary_unary(
                '/exchange.ExchangeService/GetMarketStats',
                request_serializer=exchange__pb2.MarketStatsRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketStats.FromString,
                )
        self.GetTrades = channel.unary_unary(
                '/exchange.ExchangeService/GetTrades',
                request_serializer=exchange__pb2.TradeHistoryRequest.SerializeToString,
                response_deserializer=exchange__pb2.TradeHistoryResponse.FromString,
                )
        self.PauseMarket = channel.unary_unary(
                '/exchange.ExchangeService/PauseMarket',
                request_serializer=exchange__pb2.MarketControlRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketControlResponse.FromString,
                )
        self.ResumeMarket = channel.unary_unary(
                '/exchange.ExchangeService/ResumeMarket',
                request_serializer=exchange__pb2.MarketControlRequest.SerializeToString,
                response_deserializer=exchange__pb2.MarketControlResponse.FromString,
                )
        self.SetCircuitBreakerLimit = channel.unary_unary(
                '/exchange.ExchangeService/SetCircuitBreakerLimit',
                request_serializer=exchange__pb2.CircuitBreakerConfig.SerializeToString,
                response_deserializer=exchange__pb2.MarketControlResponse.FromString,
                )
        self.Ping = channel.unary_unary(
                '/exchange.ExchangeService/Ping',
                request_serializer=exchange__pb2.Empty.SerializeToString,
                response_deserializer=exchange__pb2.PongResponse.FromString,
                )
        self.GetEngineMetrics = channel.unary_unary(
                '/exchange.ExchangeService/GetEngineMetrics',
                request_serializer=exchange__pb2.Empty.SerializeToString,
                response_deserializer=exchange__pb2.EngineMetrics.FromString,
                )


class ExchangeServiceServicer(object):
    """============================================================
    Core Service Definition
    ============================================================

    """

    def SubmitOrder(self, request, context):
        """Order lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AmendOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderBook(self, request, context):
        """Market data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMarketStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PauseMarket(self, request, context):
        """Admin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeMarket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCircuitBreakerLimit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Engine health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngineMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitOrder,
                    request_deserializer=exchange__pb2.OrderRequest.FromString,
                    response_serializer=exchange__pb2.OrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=exchange__pb2.CancelRequest.FromString,
                    response_serializer=exchange__pb2.CancelResponse.SerializeToString,
            ),
            'AmendOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.AmendOrder,
                    request_deserializer=exchange__pb2.AmendRequest.FromString,
                    response_serializer=exchange__pb2.OrderResponse.SerializeToString,
            ),
            'GetOrderBook': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderBook,
                    request_deserializer=exchange__pb2.OrderBookRequest.FromString,
                    response_serializer=exchange__pb2.OrderBookSnapshot.SerializeToString,
            ),
            'GetMarketStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMarketStats,
                    request_deserializer=exchange__pb2.MarketStatsRequest.FromString,
                    response_serializer=exchange__pb2.MarketStats.SerializeToString,
            ),
            'GetTrades': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrades,
                    request_deserializer=exchange__pb2.TradeHistoryRequest.FromString,
                    response_serializer=exchange__pb2.TradeHistoryResponse.SerializeToString,
            ),
            'PauseMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.PauseMarket,
                    request_deserializer=exchange__pb2.MarketControlRequest.FromString,
                    response_serializer=exchange__pb2.MarketControlResponse.SerializeToString,
            ),
            'ResumeMarket': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeMarket,
                    request_deserializer=exchange__pb2.MarketControlRequest.FromString,
                    response_serializer=exchange__pb2.MarketControlResponse.SerializeToString,
            ),
            'SetCircuitBreakerLimit': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCircuitBreakerLimit,
                    request_deserializer=exchange__pb2.CircuitBreakerConfig.FromString,
                    response_serializer=exchange__pb2.MarketControlResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=exchange__pb2.Empty.FromString,
                    response_serializer=exchange__pb2.PongResponse.SerializeToString,
            ),
            'GetEngineMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngineMetrics,
                    request_deserializer=exchange__pb2.Empty.FromString,
                    response_serializer=exchange__pb2.EngineMetrics.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange.ExchangeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExchangeService(object):
    """============================================================
    Core Service Definition
    ============================================================

    """

    @staticmethod
    def SubmitOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/SubmitOrder',
            exchange__pb2.OrderRequest.SerializeToString,
            exchange__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/CancelOrder',
            exchange__pb2.CancelRequest.SerializeToString,
            exchange__pb2.CancelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AmendOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/AmendOrder',
            exchange__pb2.AmendRequest.SerializeToString,
            exchange__pb2.OrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOrderBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/GetOrderBook',
            exchange__pb2.OrderBookRequest.SerializeToString,
            exchange__pb2.OrderBookSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMarketStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/GetMarketStats',
            exchange__pb2.MarketStatsRequest.SerializeToString,
            exchange__pb2.MarketStats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTrades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/GetTrades',
            exchange__pb2.TradeHistoryRequest.SerializeToString,
            exchange__pb2.TradeHistoryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PauseMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/PauseMarket',
            exchange__pb2.MarketControlRequest.SerializeToString,
            exchange__pb2.MarketControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResumeMarket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/ResumeMarket',
            exchange__pb2.MarketControlRequest.SerializeToString,
            exchange__pb2.MarketControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetCircuitBreakerLimit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/SetCircuitBreakerLimit',
            exchange__pb2.CircuitBreakerConfig.SerializeToString,
            exchange__pb2.MarketControlResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/Ping',
            exchange__pb2.Empty.SerializeToString,
            exchange__pb2.PongResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEngineMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange.ExchangeService/GetEngineMetrics',
            exchange__pb2.Empty.SerializeToString,
            exchange__pb2.EngineMetrics.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
